#! /usr/bin/python

from sys import argv
import subprocess as sp
import os, json, glob

def checkArgs():
    if len(argv) < 2:
        print "Running with current directory as root experiment directory!"
    elif len(argv) > 2:
        print "Too many input arguments!"
        printProperUsage()
        return False
    elif not os.path.isdir(os.path.abspath(argv[1])):
        print "Specified experimentPath does not exist!"
        printProperUsage()
        return False
    return True

def printProperUsage():
    print "Proper Usage:"
    print "%s [experimentPath]" % argv[0]

def getExperimentPath():
    if len(argv) == 2:
        return os.path.abspath(argv[1])
    else:
        return os.path.abspath('.')

def createDataDirectory(expPath):
    dataPath = os.path.join(expPath, '.registrationData')
    ensureDir(dataPath)
    return dataPath

def ensureDir(dirPath):
    if not os.path.exists(dirPath):
        os.mkdir(dirPath)
    elif not os.path.isdir(dirPath):
        print "Warning! Non-directory file exists at:\n\t%s" % dirPath

def createJsonFile(dataPath, imagePath):
    jsonPath = os.path.join(dataPath, 'metadata.json')
    jsonFile = open(jsonPath, 'w')
    return jsonFile, jsonPath

def populateJsonFile(j, vsiPaths):
    dictList = list()
    for vsiPath in vsiPaths:
            imDict = {'vsiPath': vsiPath}
            dictList.append(imDict)
    json.dump(dictList, j, sort_keys=True, indent=4)

def findVsis(expPath):
    vsiPaths = list()
    for root, dirs, files in os.walk(expPath):
        for filename in files:
            if filename.endswith('.vsi'):
                fullPath = os.path.join(root, filename)
                relPath = os.path.relpath(fullPath, expPath)
                vsiPaths.append(relPath)
    return vsiPaths

def main():
    argsValid = checkArgs()
    if not argsValid:
        return
    # Load filenames, and create the json file and the containing directory
    experimentPath = getExperimentPath()
    dataPath = createDataDirectory(experimentPath)
    vsiPaths = findVsis(experimentPath)
    jsonFile, jsonPath = createJsonFile(dataPath, vsiPaths)
    populateJsonFile(jsonFile, vsiPaths)
    jsonFile.close()

    # Call the matlab preprocessing function
    argStr = 'matlab -nosplash -nodesktop -r "downsampleAndSegmentVsis(\'{}\'); exit"'.format(jsonPath)
    print "argStr: " + argStr
    sp.call(argStr, shell=True, cwd=experimentPath, env=os.environ)

    print "Preprocessing Complete!"
    print "Experiment Root Path:", experimentPath
    print "Data Path:", dataPath
    print "JSON Path:", jsonPath
    

if __name__ == "__main__":
    main()